// Δίαυλος — locations-extra.js
// Επιπλέον σημεία προσβασιμότητας + «Υπηρεσίες από απόσταση».
// Τα EXTRA_LOCATIONS έχουν coords: null — οι συντεταγμένες μπαίνουν από το locations-coords.js
// (το φτιάχνει το tools/geocode-locations.html). Σημεία χωρίς συντεταγμένες δεν εμφανίζονται στον χάρτη.
// Ίδιο σχήμα με το MAP_LOCATIONS (βλ. data.js) + πεδίο address.

const EXTRA_LOCATIONS = [
  {
    "id": "iris-ky-athinon",
    "name": "Κέντρο Υγείας Αθηνών",
    "city": "Αθήνα",
    "category": "health",
    "address": "Ακαδημίας 58, Αθήνα 106 79",
    "geocodeQuery": "Ακαδημίας 58, Αθήνα",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": true,
      "iris": true,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "permanent",
    "reliability": "high",
    "note": "Σταθμός τηλεδιερμηνείας ΕΝΓ (IRIS, Εθνικό Ίδρυμα Κωφών) — tablet στο χώρο· η υπηρεσία λειτουργεί 24ωρο.",
    "source": "myiris.gr (λίστα Iris Booth)"
  },
  {
    "id": "iris-agia-sofia",
    "name": "Νοσοκομείο Παίδων «Αγία Σοφία»",
    "city": "Αθήνα",
    "category": "health",
    "address": "Θηβών 1, Αθήνα 115 27",
    "geocodeQuery": "Νοσοκομείο Παίδων Αγία Σοφία, Θηβών 1, Αθήνα",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": true,
      "iris": true,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "permanent",
    "reliability": "high",
    "note": "Σταθμός τηλεδιερμηνείας ΕΝΓ (IRIS, Εθνικό Ίδρυμα Κωφών) — tablet στο χώρο· η υπηρεσία λειτουργεί 24ωρο.",
    "source": "myiris.gr (λίστα Iris Booth)"
  },
  {
    "id": "iris-ypourgeio-ergasias",
    "name": "Υπουργείο Εργασίας",
    "city": "Αθήνα",
    "category": "public",
    "address": "Σολωμού 60, Αθήνα 104 32",
    "geocodeQuery": "Σολωμού 60, Αθήνα",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": true,
      "iris": true,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "permanent",
    "reliability": "high",
    "note": "Σταθμός τηλεδιερμηνείας ΕΝΓ (IRIS, Εθνικό Ίδρυμα Κωφών) — tablet στο χώρο· η υπηρεσία λειτουργεί 24ωρο.",
    "source": "myiris.gr (λίστα Iris Booth)"
  },
  {
    "id": "iris-kep-syntagmatos",
    "name": "ΚΕΠ Συντάγματος",
    "city": "Αθήνα",
    "category": "public",
    "address": "Όθωνος 10, Αθήνα 105 57",
    "geocodeQuery": "Όθωνος 10, Αθήνα",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": true,
      "iris": true,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "permanent",
    "reliability": "high",
    "note": "Σταθμός τηλεδιερμηνείας ΕΝΓ (IRIS, Εθνικό Ίδρυμα Κωφών) — tablet στο χώρο· η υπηρεσία λειτουργεί 24ωρο.",
    "source": "myiris.gr (λίστα Iris Booth)"
  },
  {
    "id": "iris-ippokrateio",
    "name": "Ιπποκράτειο Νοσοκομείο",
    "city": "Αθήνα",
    "category": "health",
    "address": "Βασ. Σοφίας 114, Αθήνα 115 27",
    "geocodeQuery": "Ιπποκράτειο Νοσοκομείο, Βασιλίσσης Σοφίας 114, Αθήνα",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": true,
      "iris": true,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "permanent",
    "reliability": "high",
    "note": "Σταθμός τηλεδιερμηνείας ΕΝΓ (IRIS, Εθνικό Ίδρυμα Κωφών) — tablet στο χώρο· η υπηρεσία λειτουργεί 24ωρο.",
    "source": "myiris.gr (λίστα Iris Booth)"
  },
  {
    "id": "iris-dimos-athinaion",
    "name": "Δήμος Αθηναίων — Δημοτολόγιο",
    "city": "Αθήνα",
    "category": "public",
    "address": "Αθηνάς 63, Αθήνα 105 52",
    "geocodeQuery": "Αθηνάς 63, Αθήνα",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": true,
      "iris": true,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "permanent",
    "reliability": "high",
    "note": "Σταθμός τηλεδιερμηνείας ΕΝΓ (IRIS, Εθνικό Ίδρυμα Κωφών) — tablet στο χώρο· η υπηρεσία λειτουργεί 24ωρο.",
    "source": "myiris.gr (λίστα Iris Booth)"
  },
  {
    "id": "iris-metro-syntagma",
    "name": "Σταθμός Μετρό Συντάγματος (εκδοτήρια)",
    "city": "Αθήνα",
    "category": "transport",
    "address": "Πλατεία Συντάγματος, Αθήνα",
    "geocodeQuery": "Σταθμός Μετρό Σύνταγμα, Αθήνα",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": true,
      "iris": true,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "permanent",
    "reliability": "medium",
    "note": "Σταθμός τηλεδιερμηνείας ΕΝΓ (IRIS, Εθνικό Ίδρυμα Κωφών) — tablet στο χώρο· η υπηρεσία λειτουργεί 24ωρο. Ξεκίνησε το 2020 ως πιλοτικό για 1 χρόνο· εμφανίζεται στη λίστα του myiris.gr.",
    "source": "myiris.gr (λίστα Iris Booth)"
  },
  {
    "id": "iris-pammakaristos",
    "name": "Νοσοκομείο Παμμακάριστος",
    "city": "Αθήνα (Πειραιάς)",
    "category": "health",
    "address": "Ιακωβάτων 43, Αθήνα 111 44",
    "geocodeQuery": "Νοσοκομείο Παμμακάριστος, Ιακωβάτων 43, Αθήνα",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": true,
      "iris": true,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "permanent",
    "reliability": "high",
    "note": "Σταθμός τηλεδιερμηνείας ΕΝΓ (IRIS, Εθνικό Ίδρυμα Κωφών) — tablet στο χώρο· η υπηρεσία λειτουργεί 24ωρο.",
    "source": "myiris.gr (λίστα Iris Booth)"
  },
  {
    "id": "iris-kep-peiraia",
    "name": "ΚΕΠ Πειραιά — Κεντρικό",
    "city": "Πειραιάς",
    "category": "public",
    "address": "Μακράς Στοάς 15 (ισόγειο), Πειραιάς 185 31",
    "geocodeQuery": "Μακράς Στοάς 15, Πειραιάς",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": true,
      "iris": true,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "permanent",
    "reliability": "high",
    "note": "Σταθμός τηλεδιερμηνείας ΕΝΓ (IRIS, Εθνικό Ίδρυμα Κωφών) — tablet στο χώρο· η υπηρεσία λειτουργεί 24ωρο. Εγκαινιάστηκε τον Ιούνιο 2022.",
    "source": "myiris.gr (λίστα Iris Booth)"
  },
  {
    "id": "iris-pgn-alexandroupolis",
    "name": "ΠΓΝ Αλεξανδρούπολης",
    "city": "Αλεξανδρούπολη",
    "category": "health",
    "address": "Αλεξανδρούπολη 681 00",
    "geocodeQuery": "Πανεπιστημιακό Γενικό Νοσοκομείο Αλεξανδρούπολης",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": true,
      "iris": true,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "permanent",
    "reliability": "high",
    "note": "Σταθμός τηλεδιερμηνείας ΕΝΓ (IRIS, Εθνικό Ίδρυμα Κωφών) — tablet στο χώρο· η υπηρεσία λειτουργεί 24ωρο.",
    "source": "myiris.gr (λίστα Iris Booth)"
  },
  {
    "id": "iris-nosokomeio-volou",
    "name": "Νοσοκομείο Βόλου",
    "city": "Βόλος",
    "category": "health",
    "address": "Πολυμέρη 134, Βόλος 382 22",
    "geocodeQuery": "Γενικό Νοσοκομείο Βόλου, Πολυμέρη 134, Βόλος",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": true,
      "iris": true,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "permanent",
    "reliability": "high",
    "note": "Σταθμός τηλεδιερμηνείας ΕΝΓ (IRIS, Εθνικό Ίδρυμα Κωφών) — tablet στο χώρο· η υπηρεσία λειτουργεί 24ωρο.",
    "source": "myiris.gr (λίστα Iris Booth)"
  },
  {
    "id": "iris-ky-thessalonikis",
    "name": "Κέντρο Υγείας Θεσσαλονίκης",
    "city": "Θεσσαλονίκη",
    "category": "health",
    "address": "25ης Μαρτίου 20, Θεσσαλονίκη 546 46",
    "geocodeQuery": "25ης Μαρτίου 20, Θεσσαλονίκη",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": true,
      "iris": true,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "permanent",
    "reliability": "high",
    "note": "Σταθμός τηλεδιερμηνείας ΕΝΓ (IRIS, Εθνικό Ίδρυμα Κωφών) — tablet στο χώρο· η υπηρεσία λειτουργεί 24ωρο.",
    "source": "myiris.gr (λίστα Iris Booth)"
  },
  {
    "id": "iris-ahepa",
    "name": "ΠΓΝ Θεσσαλονίκης ΑΧΕΠΑ",
    "city": "Θεσσαλονίκη",
    "category": "health",
    "address": "Κυριακίδη Στίλπωνος 1, Θεσσαλονίκη 546 36",
    "geocodeQuery": "ΑΧΕΠΑ, Στίλπωνος Κυριακίδη 1, Θεσσαλονίκη",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": true,
      "iris": true,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "permanent",
    "reliability": "high",
    "note": "Σταθμός τηλεδιερμηνείας ΕΝΓ (IRIS, Εθνικό Ίδρυμα Κωφών) — tablet στο χώρο· η υπηρεσία λειτουργεί 24ωρο.",
    "source": "myiris.gr (λίστα Iris Booth)"
  },
  {
    "id": "iris-ky-ioanninon",
    "name": "Κέντρο Υγείας Ιωαννίνων",
    "city": "Ιωάννινα",
    "category": "health",
    "address": "Π. Μελά 54, Ιωάννινα 454 44",
    "geocodeQuery": "Παύλου Μελά 54, Ιωάννινα",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": true,
      "iris": true,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "permanent",
    "reliability": "high",
    "note": "Σταθμός τηλεδιερμηνείας ΕΝΓ (IRIS, Εθνικό Ίδρυμα Κωφών) — tablet στο χώρο· η υπηρεσία λειτουργεί 24ωρο.",
    "source": "myiris.gr (λίστα Iris Booth)"
  },
  {
    "id": "iris-pgn-ioanninon",
    "name": "ΠΓΝ Ιωαννίνων",
    "city": "Ιωάννινα",
    "category": "health",
    "address": "Οδός Σταύρου Νιάρχου, Ιωάννινα 455 00",
    "geocodeQuery": "Πανεπιστημιακό Γενικό Νοσοκομείο Ιωαννίνων",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": true,
      "iris": true,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "permanent",
    "reliability": "high",
    "note": "Σταθμός τηλεδιερμηνείας ΕΝΓ (IRIS, Εθνικό Ίδρυμα Κωφών) — tablet στο χώρο· η υπηρεσία λειτουργεί 24ωρο.",
    "source": "myiris.gr (λίστα Iris Booth)"
  },
  {
    "id": "iris-ky-patras",
    "name": "Κέντρο Υγείας Βορείου Τομέα Πάτρας",
    "city": "Πάτρα",
    "category": "health",
    "address": "Γιαννιτσών 3, Πάτρα 262 23",
    "geocodeQuery": "Γιαννιτσών 3, Πάτρα",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": true,
      "iris": true,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "permanent",
    "reliability": "high",
    "note": "Σταθμός τηλεδιερμηνείας ΕΝΓ (IRIS, Εθνικό Ίδρυμα Κωφών) — tablet στο χώρο· η υπηρεσία λειτουργεί 24ωρο.",
    "source": "myiris.gr (λίστα Iris Booth)"
  },
  {
    "id": "iris-pgn-patras-rio",
    "name": "ΠΓΝ Πατρών (Ρίο)",
    "city": "Πάτρα (Ρίο)",
    "category": "health",
    "address": "Ρίο, Πάτρα 265 04",
    "geocodeQuery": "Πανεπιστημιακό Γενικό Νοσοκομείο Πατρών, Ρίο",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": true,
      "iris": true,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "permanent",
    "reliability": "medium",
    "note": "Σταθμός τηλεδιερμηνείας ΕΝΓ (IRIS, Εθνικό Ίδρυμα Κωφών) — tablet στο χώρο· η υπηρεσία λειτουργεί 24ωρο. Στη λίστα του myiris.gr αναφέρεται «σύντομα»· άρθρο του 2020 το αναφέρει ως λειτουργούν.",
    "source": "myiris.gr (λίστα Iris Booth)"
  },
  {
    "id": "iris-mamatseio",
    "name": "Μαμάτσειο Νοσοκομείο",
    "city": "Κοζάνη",
    "category": "health",
    "address": "Κ. Μαμάτσιου 1, Κοζάνη 501 31",
    "geocodeQuery": "Μαμάτσειο Νοσοκομείο, Κοζάνη",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": true,
      "iris": true,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "permanent",
    "reliability": "high",
    "note": "Σταθμός τηλεδιερμηνείας ΕΝΓ (IRIS, Εθνικό Ίδρυμα Κωφών) — tablet στο χώρο· η υπηρεσία λειτουργεί 24ωρο.",
    "source": "myiris.gr (λίστα Iris Booth)"
  },
  {
    "id": "iris-dimos-kozanis",
    "name": "Δήμος Κοζάνης",
    "city": "Κοζάνη",
    "category": "public",
    "address": "Πλατεία Νίκης 1, Κοζάνη 501 31",
    "geocodeQuery": "Δημαρχείο Κοζάνης, Πλατεία Νίκης 1",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": true,
      "iris": true,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "permanent",
    "reliability": "high",
    "note": "Σταθμός τηλεδιερμηνείας ΕΝΓ (IRIS, Εθνικό Ίδρυμα Κωφών) — tablet στο χώρο· η υπηρεσία λειτουργεί 24ωρο.",
    "source": "myiris.gr (λίστα Iris Booth)"
  },
  {
    "id": "iris-deya-kozanis",
    "name": "ΔΕΥΑ Κοζάνης",
    "city": "Κοζάνη",
    "category": "public",
    "address": "2ο χλμ Κοζάνης–Θεσσαλονίκης, Κοζάνη 501 00",
    "geocodeQuery": "ΔΕΥΑ Κοζάνης",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": true,
      "iris": true,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "permanent",
    "reliability": "high",
    "note": "Σταθμός τηλεδιερμηνείας ΕΝΓ (IRIS, Εθνικό Ίδρυμα Κωφών) — tablet στο χώρο· η υπηρεσία λειτουργεί 24ωρο.",
    "source": "myiris.gr (λίστα Iris Booth)"
  },
  {
    "id": "iris-perifereia-dyt-makedonias",
    "name": "Περιφέρεια Δυτικής Μακεδονίας",
    "city": "Κοζάνη",
    "category": "public",
    "address": "Δημοκρατίας 27, Κοζάνη 501 31",
    "geocodeQuery": "Δημοκρατίας 27, Κοζάνη",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": true,
      "iris": true,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "permanent",
    "reliability": "high",
    "note": "Σταθμός τηλεδιερμηνείας ΕΝΓ (IRIS, Εθνικό Ίδρυμα Κωφών) — tablet στο χώρο· η υπηρεσία λειτουργεί 24ωρο.",
    "source": "myiris.gr (λίστα Iris Booth)"
  },
  {
    "id": "iris-ky-irakleiou",
    "name": "Κέντρο Υγείας Ηρακλείου",
    "city": "Ηράκλειο",
    "category": "health",
    "address": "3ο χλμ Εθνικής Οδού Ηρακλείου–Μοιρών, Εσταυρωμένος, 715 00",
    "geocodeQuery": "Κέντρο Υγείας Εσταυρωμένου Ηρακλείου",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": true,
      "iris": true,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "permanent",
    "reliability": "high",
    "note": "Σταθμός τηλεδιερμηνείας ΕΝΓ (IRIS, Εθνικό Ίδρυμα Κωφών) — tablet στο χώρο· η υπηρεσία λειτουργεί 24ωρο.",
    "source": "myiris.gr (λίστα Iris Booth)"
  },
  {
    "id": "iris-pagni",
    "name": "ΠΑΓΝΗ",
    "city": "Ηράκλειο",
    "category": "health",
    "address": "Λεωφόρος Πανεπιστημίου, Ηράκλειο 715 00",
    "geocodeQuery": "ΠΑΓΝΗ Πανεπιστημιακό Γενικό Νοσοκομείο Ηρακλείου",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": true,
      "iris": true,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "permanent",
    "reliability": "high",
    "note": "Σταθμός τηλεδιερμηνείας ΕΝΓ (IRIS, Εθνικό Ίδρυμα Κωφών) — tablet στο χώρο· η υπηρεσία λειτουργεί 24ωρο.",
    "source": "myiris.gr (λίστα Iris Booth)"
  },
  {
    "id": "iris-dimos-chanion",
    "name": "Δήμος Χανίων",
    "city": "Χανιά",
    "category": "public",
    "address": "Κυδωνίας 29, Χανιά 731 35",
    "geocodeQuery": "Κυδωνίας 29, Χανιά",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": true,
      "iris": true,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "permanent",
    "reliability": "high",
    "note": "Σταθμός τηλεδιερμηνείας ΕΝΓ (IRIS, Εθνικό Ίδρυμα Κωφών) — tablet στο χώρο· η υπηρεσία λειτουργεί 24ωρο.",
    "source": "myiris.gr (λίστα Iris Booth)"
  },
  {
    "id": "iris-gn-trikalon",
    "name": "ΓΝ Τρικάλων",
    "city": "Τρίκαλα",
    "category": "health",
    "address": "Καρδίτσης 56, Τρίκαλα 421 00",
    "geocodeQuery": "Γενικό Νοσοκομείο Τρικάλων, Καρδίτσης 56",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": true,
      "iris": true,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "permanent",
    "reliability": "high",
    "note": "Σταθμός τηλεδιερμηνείας ΕΝΓ (IRIS, Εθνικό Ίδρυμα Κωφών) — tablet στο χώρο· η υπηρεσία λειτουργεί 24ωρο.",
    "source": "myiris.gr (λίστα Iris Booth)"
  },
  {
    "id": "praktiker-agia-varvara",
    "name": "Praktiker Αγ. Βαρβάρα",
    "city": "Αγία Βαρβάρα",
    "category": "retail",
    "address": "Ιερά Οδός 339, Αγ. Βαρβάρα 123 51",
    "geocodeQuery": "Praktiker, Ιερά Οδός 339, Αγία Βαρβάρα",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": false,
      "iris": false,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "on-request",
    "reliability": "medium",
    "note": "Διερμηνεία ΕΝΓ μέσα στο κατάστημα, κατόπιν ραντεβού (φόρμα στο praktiker.gr). Οι διερμηνείς της HandsUp συνδέονται μέσω του δικού σου κινητού. Ανακοινώθηκε το 2023 για όλα τα καταστήματα· επιβεβαίωσε πριν πας.",
    "source": "praktiker.gr/Stores · hands-up.org"
  },
  {
    "id": "praktiker-alexandroupoli",
    "name": "Praktiker Αλεξανδρούπολη",
    "city": "Αλεξανδρούπολη",
    "category": "retail",
    "address": "3ο χλμ, Αλεξανδρούπολη 681 00",
    "geocodeQuery": "Praktiker Αλεξανδρούπολη",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": false,
      "iris": false,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "on-request",
    "reliability": "medium",
    "note": "Διερμηνεία ΕΝΓ μέσα στο κατάστημα, κατόπιν ραντεβού (φόρμα στο praktiker.gr). Οι διερμηνείς της HandsUp συνδέονται μέσω του δικού σου κινητού. Ανακοινώθηκε το 2023 για όλα τα καταστήματα· επιβεβαίωσε πριν πας.",
    "source": "praktiker.gr/Stores · hands-up.org"
  },
  {
    "id": "praktiker-volos",
    "name": "Praktiker Βόλος",
    "city": "Βόλος",
    "category": "retail",
    "address": "Αρ. Ζάχου & Μητροπολίτου Γρηγορίου, Βόλος 383 34",
    "geocodeQuery": "Αρ. Ζάχου και Μητροπολίτου Γρηγορίου, Βόλος",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": false,
      "iris": false,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "on-request",
    "reliability": "medium",
    "note": "Διερμηνεία ΕΝΓ μέσα στο κατάστημα, κατόπιν ραντεβού (φόρμα στο praktiker.gr). Οι διερμηνείς της HandsUp συνδέονται μέσω του δικού σου κινητού. Ανακοινώθηκε το 2023 για όλα τα καταστήματα· επιβεβαίωσε πριν πας.",
    "source": "praktiker.gr/Stores · hands-up.org"
  },
  {
    "id": "praktiker-elliniko",
    "name": "Praktiker Ελληνικό",
    "city": "Ελληνικό",
    "category": "retail",
    "address": "Αγ. Παρασκευής & Τιτάνων 2, Ελληνικό 167 77",
    "geocodeQuery": "Αγίας Παρασκευής 2, Ελληνικό",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": false,
      "iris": false,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "on-request",
    "reliability": "medium",
    "note": "Διερμηνεία ΕΝΓ μέσα στο κατάστημα, κατόπιν ραντεβού (φόρμα στο praktiker.gr). Οι διερμηνείς της HandsUp συνδέονται μέσω του δικού σου κινητού. Ανακοινώθηκε το 2023 για όλα τα καταστήματα· επιβεβαίωσε πριν πας.",
    "source": "praktiker.gr/Stores · hands-up.org"
  },
  {
    "id": "praktiker-irakleio",
    "name": "Praktiker Ηράκλειο Κρήτης",
    "city": "Νέα Αλικαρνασσός, Ηράκλειο",
    "category": "retail",
    "address": "Καρτερού 22, Νέα Αλικαρνασσός 716 01",
    "geocodeQuery": "Καρτερού 22, Ηράκλειο",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": false,
      "iris": false,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "on-request",
    "reliability": "medium",
    "note": "Διερμηνεία ΕΝΓ μέσα στο κατάστημα, κατόπιν ραντεβού (φόρμα στο praktiker.gr). Οι διερμηνείς της HandsUp συνδέονται μέσω του δικού σου κινητού. Ανακοινώθηκε το 2023 για όλα τα καταστήματα· επιβεβαίωσε πριν πας.",
    "source": "praktiker.gr/Stores · hands-up.org"
  },
  {
    "id": "praktiker-thessaloniki",
    "name": "Praktiker Θεσσαλονίκη",
    "city": "Πυλαία, Θεσσαλονίκη",
    "category": "retail",
    "address": "Μαρίνου Αντύπα 34, Πυλαία-Χορτιάτης 555 35",
    "geocodeQuery": "Μαρίνου Αντύπα 34, Πυλαία",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": false,
      "iris": false,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "on-request",
    "reliability": "medium",
    "note": "Διερμηνεία ΕΝΓ μέσα στο κατάστημα, κατόπιν ραντεβού (φόρμα στο praktiker.gr). Οι διερμηνείς της HandsUp συνδέονται μέσω του δικού σου κινητού. Ανακοινώθηκε το 2023 για όλα τα καταστήματα· επιβεβαίωσε πριν πας.",
    "source": "praktiker.gr/Stores · hands-up.org"
  },
  {
    "id": "praktiker-ioannina",
    "name": "Praktiker Ιωάννινα",
    "city": "Ιωάννινα",
    "category": "retail",
    "address": "6ο χλμ. Εθνικής Οδού Ιωαννίνων–Άρτας, Ιωάννινα 455 00",
    "geocodeQuery": "Praktiker Ιωάννινα",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": false,
      "iris": false,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "on-request",
    "reliability": "medium",
    "note": "Διερμηνεία ΕΝΓ μέσα στο κατάστημα, κατόπιν ραντεβού (φόρμα στο praktiker.gr). Οι διερμηνείς της HandsUp συνδέονται μέσω του δικού σου κινητού. Ανακοινώθηκε το 2023 για όλα τα καταστήματα· επιβεβαίωσε πριν πας.",
    "source": "praktiker.gr/Stores · hands-up.org"
  },
  {
    "id": "praktiker-kalamata",
    "name": "Praktiker Καλαμάτα",
    "city": "Θουρία, Καλαμάτα",
    "category": "retail",
    "address": "7ο χλμ. Εθνικής Οδού Καλαμάτας–Τριπόλεως, Θουρία 240 09",
    "geocodeQuery": "Praktiker Καλαμάτα",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": false,
      "iris": false,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "on-request",
    "reliability": "medium",
    "note": "Διερμηνεία ΕΝΓ μέσα στο κατάστημα, κατόπιν ραντεβού (φόρμα στο praktiker.gr). Οι διερμηνείς της HandsUp συνδέονται μέσω του δικού σου κινητού. Ανακοινώθηκε το 2023 για όλα τα καταστήματα· επιβεβαίωσε πριν πας.",
    "source": "praktiker.gr/Stores · hands-up.org"
  },
  {
    "id": "praktiker-kerkyra",
    "name": "Praktiker Κέρκυρα",
    "city": "Γαστούρι, Κέρκυρα",
    "category": "retail",
    "address": "5ο χλμ. Εθνικής, Γαστούρι 490 84",
    "geocodeQuery": "Praktiker Κέρκυρα Γαστούρι",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": false,
      "iris": false,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "on-request",
    "reliability": "medium",
    "note": "Διερμηνεία ΕΝΓ μέσα στο κατάστημα, κατόπιν ραντεβού (φόρμα στο praktiker.gr). Οι διερμηνείς της HandsUp συνδέονται μέσω του δικού σου κινητού. Ανακοινώθηκε το 2023 για όλα τα καταστήματα· επιβεβαίωσε πριν πας.",
    "source": "praktiker.gr/Stores · hands-up.org"
  },
  {
    "id": "praktiker-larisa",
    "name": "Praktiker Λάρισα",
    "city": "Λάρισα",
    "category": "retail",
    "address": "Λαρίσης Τρικάλων & Φαρσάλων, Λάρισα 415 00",
    "geocodeQuery": "Praktiker Λάρισα",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": false,
      "iris": false,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "on-request",
    "reliability": "medium",
    "note": "Διερμηνεία ΕΝΓ μέσα στο κατάστημα, κατόπιν ραντεβού (φόρμα στο praktiker.gr). Οι διερμηνείς της HandsUp συνδέονται μέσω του δικού σου κινητού. Ανακοινώθηκε το 2023 για όλα τα καταστήματα· επιβεβαίωσε πριν πας.",
    "source": "praktiker.gr/Stores · hands-up.org"
  },
  {
    "id": "praktiker-mandra",
    "name": "Praktiker Μάνδρα",
    "city": "Μάνδρα-Ειδυλλία",
    "category": "retail",
    "address": "Μυκηνών, 23ο χλμ Νέας Εθνικής Οδού Αθηνών–Κορίνθου, Μάνδρα 196 00",
    "geocodeQuery": "Praktiker Μάνδρα",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": false,
      "iris": false,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "on-request",
    "reliability": "medium",
    "note": "Διερμηνεία ΕΝΓ μέσα στο κατάστημα, κατόπιν ραντεβού (φόρμα στο praktiker.gr). Οι διερμηνείς της HandsUp συνδέονται μέσω του δικού σου κινητού. Ανακοινώθηκε το 2023 για όλα τα καταστήματα· επιβεβαίωσε πριν πας.",
    "source": "praktiker.gr/Stores · hands-up.org"
  },
  {
    "id": "praktiker-metamorfosi",
    "name": "Praktiker Μεταμόρφωση",
    "city": "Μεταμόρφωση, Αττική",
    "category": "retail",
    "address": "Τατοΐου 14, Μεταμόρφωση 144 51",
    "geocodeQuery": "Τατοΐου 14, Μεταμόρφωση",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": false,
      "iris": false,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "on-request",
    "reliability": "medium",
    "note": "Διερμηνεία ΕΝΓ μέσα στο κατάστημα, κατόπιν ραντεβού (φόρμα στο praktiker.gr). Οι διερμηνείς της HandsUp συνδέονται μέσω του δικού σου κινητού. Ανακοινώθηκε το 2023 για όλα τα καταστήματα· επιβεβαίωσε πριν πας.",
    "source": "praktiker.gr/Stores · hands-up.org"
  },
  {
    "id": "praktiker-xanthi",
    "name": "Praktiker Ξάνθη",
    "city": "Ξάνθη",
    "category": "retail",
    "address": "Flamingo Retail Park, 5ο χλμ ΕΟ Ξάνθης–Κομοτηνής, Ξάνθη 671 00",
    "geocodeQuery": "Flamingo Retail Park, Ξάνθη",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": false,
      "iris": false,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "on-request",
    "reliability": "medium",
    "note": "Διερμηνεία ΕΝΓ μέσα στο κατάστημα, κατόπιν ραντεβού (φόρμα στο praktiker.gr). Οι διερμηνείς της HandsUp συνδέονται μέσω του δικού σου κινητού. Ανακοινώθηκε το 2023 για όλα τα καταστήματα· επιβεβαίωσε πριν πας.",
    "source": "praktiker.gr/Stores · hands-up.org"
  },
  {
    "id": "praktiker-pallini",
    "name": "Praktiker Παλλήνη",
    "city": "Ανθούσα, Αττική",
    "category": "retail",
    "address": "Πρώην Expo Athens, Emporium Plaza, Λεωφ. Ανθούσας & Ντραφίου, Ανθούσα 153 49",
    "geocodeQuery": "Emporium Plaza, Ανθούσα",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": false,
      "iris": false,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "on-request",
    "reliability": "medium",
    "note": "Διερμηνεία ΕΝΓ μέσα στο κατάστημα, κατόπιν ραντεβού (φόρμα στο praktiker.gr). Οι διερμηνείς της HandsUp συνδέονται μέσω του δικού σου κινητού. Ανακοινώθηκε το 2023 για όλα τα καταστήματα· επιβεβαίωσε πριν πας.",
    "source": "praktiker.gr/Stores · hands-up.org"
  },
  {
    "id": "praktiker-patra",
    "name": "Praktiker Πάτρα",
    "city": "Πάτρα",
    "category": "retail",
    "address": "Ακτή Δυμαίων 56-58, Πάτρα 263 33",
    "geocodeQuery": "Ακτή Δυμαίων 56, Πάτρα",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": false,
      "iris": false,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "on-request",
    "reliability": "medium",
    "note": "Διερμηνεία ΕΝΓ μέσα στο κατάστημα, κατόπιν ραντεβού (φόρμα στο praktiker.gr). Οι διερμηνείς της HandsUp συνδέονται μέσω του δικού σου κινητού. Ανακοινώθηκε το 2023 για όλα τα καταστήματα· επιβεβαίωσε πριν πας.",
    "source": "praktiker.gr/Stores · hands-up.org"
  },
  {
    "id": "praktiker-rodos",
    "name": "Praktiker Ρόδος",
    "city": "Ρόδος",
    "category": "retail",
    "address": "Ηλία Βενέζη, Ρόδος 851 00",
    "geocodeQuery": "Ηλία Βενέζη, Ρόδος",
    "coords": null,
    "features": {
      "signLanguage": false,
      "signLanguageVideo": true,
      "tabletDevices": false,
      "iris": false,
      "hearingLoop": false,
      "liveCaptions": false,
      "writtenComm": true,
      "lipReading": false,
      "deafStaff": false
    },
    "interpreter": "remote",
    "availability": "on-request",
    "reliability": "medium",
    "note": "Διερμηνεία ΕΝΓ μέσα στο κατάστημα, κατόπιν ραντεβού (φόρμα στο praktiker.gr). Οι διερμηνείς της HandsUp συνδέονται μέσω του δικού σου κινητού. Ανακοινώθηκε το 2023 για όλα τα καταστήματα· επιβεβαίωσε πριν πας.",
    "source": "praktiker.gr/Stores · hands-up.org"
  }
];

// Υπηρεσίες που δεν συνδέονται με συγκεκριμένο σημείο (βιντεοκλήση / εφαρμογή).
const REMOTE_SERVICES = [
  {
    "id": "rs-iris",
    "name": "IRIS — Relay Service (Εθνικό Ίδρυμα Κωφών)",
    "what": "Δωρεάν τηλεδιερμηνεία στην ΕΝΓ και χειλεανάγνωση, 24 ώρες το 24ωρο, 365 μέρες. Για γιατρό, νοσοκομείο, δημόσιες υπηρεσίες, τράπεζα και καθημερινές συναλλαγές.",
    "how": "Εγκατάσταση της εφαρμογής IRIS στο κινητό ή τον υπολογιστή (απαιτείται εγγραφή).",
    "hours": "24/7",
    "url": "https://myiris.gr/",
    "source": "myiris.gr · Εθνικό Ίδρυμα Κωφών"
  },
  {
    "id": "rs-kotsovolos",
    "name": "Κωτσόβολος — βιντεοκλήση στη νοηματική",
    "what": "Εξυπηρέτηση στην ΕΝΓ από εκπαιδευμένο εκπρόσωπο, μέσα από το chat του kotsovolos.gr. Δεν γίνεται μέσα στα καταστήματα.",
    "how": "Άνοιξε το chat στο kotsovolos.gr και διάλεξε βιντεοκλήση.",
    "hours": "Σύμφωνα με την εταιρεία, υπάρχουν πάντα τουλάχιστον 2 άτομα για αυτή τη διαδικασία.",
    "url": "https://www.kotsovolos.gr/",
    "source": "blog.kotsovolos.gr · cnn.gr"
  },
  {
    "id": "rs-cosmote",
    "name": "COSMOTE — βιντεοκλήση στη νοηματική",
    "what": "Εξυπηρέτηση πελατών στην ΕΝΓ με βιντεοκλήση για όλα τα προϊόντα (κινητή, σταθερή, internet, TV). Το 2019 ανακοινώθηκε και σε καταστήματα με ειδική σήμανση — δεν βρέθηκε σημερινή λίστα καταστημάτων.",
    "how": "Βιντεοκλήση από το cosmotecare.gr (φόρμα).",
    "hours": "Δευτέρα–Παρασκευή 09:00–21:00 (ανακοίνωση 2019)",
    "url": "https://www.cosmotecare.gr/",
    "source": "liberal.gr · techpress.gr"
  },
  {
    "id": "rs-dei",
    "name": "ΔΕΗ — υπηρεσία για κωφούς και βαρήκοους",
    "what": "Βιντεοκλήση με εκπρόσωπο εξυπηρέτησης, παρουσία διερμηνέα ΕΝΓ, για συμβάσεις, διακανονισμούς και λογαριασμούς.",
    "how": "Κλείσε ραντεβού στο serviceforall.gr (στοιχεία, κωδικός μιας χρήσης, ημέρα/ώρα).",
    "hours": "Δευτέρα–Παρασκευή 09:00–21:00 (άρθρο 2022)",
    "url": "https://serviceforall.gr/",
    "source": "athensvoice.gr"
  },
  {
    "id": "rs-eurobank",
    "name": "Eurobank — v-Banking στη νοηματική",
    "what": "Εξυπηρέτηση κωφών και βαρήκοων πελατών με βιντεοκλήση στην ΕΝΓ, με προσωπικό σύμβουλο που ξέρει τις ανάγκες και το ιστορικό σου.",
    "how": "Εγγραφή στο v-Banking από το eurobank.gr.",
    "hours": "",
    "url": "https://www.eurobank.gr/",
    "source": "eoty.gr (2024) · eurobank.gr"
  },
  {
    "id": "rs-piraeus",
    "name": "Τράπεζα Πειραιώς — Digital Onboarding",
    "what": "Για νέους ιδιώτες πελάτες: λογαριασμός, κάρτα και κωδικοί e-banking με βιντεοκλήση από υπάλληλο εκπαιδευμένο στις βασικές αρχές της ΕΝΓ.",
    "how": "Μέσω της υπηρεσίας Digital Onboarding της τράπεζας.",
    "hours": "",
    "url": "https://www.piraeusbank.gr/",
    "source": "eoty.gr (2024)"
  },
  {
    "id": "rs-alpha",
    "name": "Alpha Bank — Remote Hub",
    "what": "Βιντεοκλήση με εξειδικευμένο εκπρόσωπο. (Από προηγούμενη καταχώριση — δεν επανελέγχθηκε.)",
    "how": "Από το alpha.gr.",
    "hours": "",
    "url": "https://www.alpha.gr/",
    "source": "alpha.gr"
  },
  {
    "id": "rs-athens-airport",
    "name": "Αεροδρόμιο Αθηνών — βιντεοκλήση με διερμηνέα ΕΝΓ",
    "what": "Ραντεβού με διερμηνέα νοηματικής και εκπρόσωπο εξυπηρέτησης πριν την άφιξη, ή επικοινωνία σε πραγματικό χρόνο με το προσωπικό (πλατφόρμα EVENLY).",
    "how": "Δες τη σελίδα «Επιβάτες με αναπηρία» του αεροδρομίου.",
    "hours": "",
    "url": "https://athens-international-airport.com/passengers-with-disabilities/",
    "source": "athens-international-airport.com"
  },
  {
    "id": "rs-1555",
    "name": "Υπουργείο Εργασίας — 1555",
    "what": "Βιντεοκλήση στην ΕΝΓ για ΕΦΚΑ, ΟΠΕΚΑ, ΔΥΠΑ. (Από προηγούμενη καταχώριση — δεν επανελέγχθηκε.)",
    "how": "Μέσω 1555.gov.gr.",
    "hours": "Δευτέρα–Παρασκευή 09:00–17:00",
    "url": "",
    "source": "ypergasias.gov.gr"
  }
];
